version: "3.7"
services:
  datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:285.0.1
    ports:
      - "8081:8081"
#    environment:
#      CLOUDSDK_CORE_PROJECT: cloud-testing
    command: "gcloud beta emulators datastore start --project cloud-testing --host-port=0.0.0.0:8081"

  pub-sub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:285.0.1
    ports:
      - "8085:8085"
#    environment:
#      CLOUDSDK_CORE_PROJECT: cloud-testing
    command: "gcloud beta emulators pubsub start --project cloud-testing --host-port=0.0.0.0:8085"
